# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Categories: categories
  Archives: archives
  About: about
  Udacity: Udacity-FrontEndDeveloper
rss: /atom.xml


# Set default keywords (Use a comma to separate)
keywords: "Front End, Fotos, Astronomy, Dubheee"

# Put your favicon.ico into `hexo-site/themes/hipaper/source/` directory.
favicon: css/images/favicon.ico


# Put your avatar.jpg into `hexo-site/themes/hipaper/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar: 
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg

# AboutPage background, support multiple images.
# https://source.unsplash.com/collection/954550/1920x1080, https://source.unsplash.com/collection/954550/1920x1081

about_big_image: [css/images/post03.jpg, https://source.unsplash.com/collection/1915310/1920x1080, https://source.unsplash.com/collection/1915145/1920x1080, https://source.unsplash.com/jn5X_BfQGlY/1920x1080, https://source.unsplash.com/-w_zNLeXBEw/1920x1080]


# Homepage thumbnail
random_thumb: true


# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
- search
- social
- recent_posts
- category
- tag
- tagcloud
- archive

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/ZhangDubhe
  Instagram: https://www.instagram.com/zht_dubhe/
  Envelope: mailto:zht_dubhe@163.com?Subject=FromUmaContact
  RSS: https://zhangdubhe.github.io/atom.xml

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
duoshuo_shortname:
disqus_shortname:
livere_shortname:
uyan_uid: 
wumii: 
valine:
  enable: true
  appid: uOIjeRxObhHWgN9xCGKv92Rx-gzGzoHsz # your leancloud application appid
  appkey: fbUT7JPnaSzmH8VO8huIa2Pl # your leancloud application appkey
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 说点什么吗？

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: jGP_xfR9GYCeqs8_nVBocFwuparYt4pPDtZs10fJZjI
baidu_site_verification: Nuy1H0R1fD
qihu_site_verification:

# Miscellaneous
google_analytics: UA-116459618-1
gauges_analytics:
baidu_analytics: e244682b41f1b3ce7b42513a3c986b70
tencent_analytics:
busuanzi_analytics: true
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 
